[options]
work_mode = "sys"
library = "Gly"
version = "2"
girs_directories = ["../../gir-files", "../../"]
min_cfg_version = "2.0.1"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

ignore = [
]
