[options]
girs_directories = ["../gir-files", "../"]
library = "Gly"
version = "2"
min_cfg_version = "2.0.1"
target_path = "."
use_gi_docgen = true
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true
generate_builder = true
trust_return_value_nullability = true
concurrency = "send+sync"

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

generate = [
    "Gly.Creator",
    "Gly.EncodedImage",
    "Gly.Frame",
    "Gly.FrameRequest",
    "Gly.Image",
    "Gly.Loader",
    "Gly.MemoryFormat",
    "Gly.MemoryFormatSelection",
    "Gly.NewFrame",
    "Gly.SandboxSelector",
]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.InputStream",
]

[[object]]
name = "Gly.Cicp"
status = "generate"
boxed_inline = true
